server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/stock
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            mapper:
              BaseMapper=DEBUG:

redis:
  sdk:
    config:
      host: localhost
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true