server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/stock
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host:  localhost
    port:  16379
    database: 0
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          core:
            mapper:
              BaseMapper=DEBUG: