version: '3.9'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: chx
      MYSQL_PASSWORD: 123456
    ports:
      - "13306:3306"
  redis:
    image: redis:7.2.0
    container_name: redis
    ports:
      - 6379:6379
